---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: podinfo-dev-new
  namespace: dev-new
  annotations:
    fluxcd.io/automated: "false"
    filter.fluxcd.io/chart-image: glob:dev-*
spec:
  releaseName: podinfo-dev-new
  chart:
    git: git@github.com:yashghia/helm-operator-get-started
    path: charts/podinfo-new
    ref: dev
  valuesFrom:
    - externalSourceRef:
        url: https://github.com/yashghia/helm-operator-get-started/blob/dev/values/devenv_values.yaml


  # valuesFrom:
  # - chartFileRef:
  #     path: ../../values/devenv_values.yaml

    
  # values:
  #   image:
  #     repository: yashghia/podinfo
  #     tag: dev-u1ccpi1q
  #   replicaCount: 1
  #   hpa:
  #     enabled: false
